[package]
name = "cacti_cuffi"
version = "0.1.0-devel"
edition = "2018"
license = "MIT OR Apache-2.0"
workspace = ".."

[features]
default = []
experimental = []

[dependencies]
libc = { path = "../../libc" }
libloading = { path = "../../libloading" }
once_cell = { path = "../../once_cell" }
