[package]
name = "cacti"
version = "0.1.0-devel"
edition = "2018"

[profile.release]
overflow-checks = true
panic = "abort"
codegen-units = 1
incremental = false

[features]
default = ["gpu"]
gpu = ["cacti_cuffi", "futhark_ffi"]

[dependencies]
cacti_cuffi = { path = "cacti_cuffi", optional = true }
futhark_ffi = { path = "dep/futhark_ffi", optional = true }
msgpack_serialize = { path = "dep/msgpack_serialize" }
repugnant_pickle = { path = "dep/repugnant_pickle" }

[[bin]]
name = "inspect_pth"
path = "tools/inspect_pth.rs"
